# Generated by Django 5.0 on 2024-01-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500, unique=True)),
                ('Content', models.TextField(max_length=1000)),
                ('Category', models.CharField(max_length=500)),
            ],
        ),
    ]
